{
 "title": "Pizza Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Authentications / Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(authentication_requests_total{status=\"success\"}[1m])",
     "legendFormat": "Successful Authentications"
    },
    {
     "expr": "rate(authentication_requests_total{status=\"failure\"}[1m])",
     "legendFormat": "Failed Authentications"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "active_users_total", "legendFormat": "Active Users" }
   ]
  },
  {
   "title": "Pizza Orders",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(pizza_purchase_pizza_total{status=\"success\"}[1m])",
     "legendFormat": "Pizzas Ordered"
    },
    {
     "expr": "rate(pizza_purchase_requests_total{status=\"failure\"}[1m])",
     "legendFormat": "PIzza Orders Failed"
    }
   ]
  },
  {
   "title": "Revenue / Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "rate(pizza_purchase_price_total{status=\"success\"}[1m])",
     "legendFormat": "Revenue"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "gauge",
   "description": "CPU and Memory Usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "cpu_percent", "legendFormat": "CPU Usage" },
    { "expr": "memory_percent", "legendFormat": "Memory Usage" }
   ]
  },
  {
   "title": "HTTP Requests / Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "sum(rate(requests_total[1m]))", "legendFormat": "Total" },
    {
     "expr": "sum by(method) (rate(requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg(request_latency_milliseconds_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg(pizza_purchase_latency_milliseconds_total)",
     "legendFormat": "Pizza Creation Latency"
    }
   ]
  }
 ]
}